# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
remote_theme:     fongandrew/hydeout
title:            복별SW
tagline:          'A Jekyll theme'
description:      '안녕하세요. Computer vision, ROS(제어), System prograiming에 관심이 많은 복별입니다. 잘 부탁드립니다. ^^7'
url:              https://luckydipper.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname: https-luckydipper-github-io

google_analytics: 'G-HGRYM1FWJR'
